.gitignore, build.gradle, gradle.properties, module.auth-service/build.gradle, module.auth-service/src/main/java/ru/botanica/AuthServiceApplication.java, module.plant-service/build.gradle, module.plant-service/src/main/java/ru/botanica/PlantServiceApplication.java, module.user-service/build.gradle, module.user-service/src/main/java/ru/botanica/UserServiceApplication.java, module.webapi/build.gradle, module.webapi/src/main/java/ru/botanica/WebApiApplication.java, settings.gradle
Добавлен каркас модульного проекта на Gradle.
Произведена первичная настройка .gitignore, параметров сборки Gradle.
Добавлены базовые зависимости spring-boot.
=> Добавлен каркас проекта

module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/entities/plants/PlantDtoMapper.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java
1. Добавлено получение данных конкретного растения со стороны Plant-Service.
2. Добавлен тестовый класс.
3. Добавлены тесты.
4. Для уменьшения зависимостей: класс PlantDtoMapper.java переделан в финальный, его методы - в статические.
=> Добавлено получение данных конкретного растения

module.auth-service/build.gradle, module.auth-service/src/main/java/ru/botanica/configs/SecurityConfig.java, module.auth-service/src/main/java/ru/botanica/controllers/AuthController.java, module.auth-service/src/main/java/ru/botanica/dto/AppError.java, module.auth-service/src/main/java/ru/botanica/dto/JwtRequest.java, module.auth-service/src/main/java/ru/botanica/dto/JwtResponse.java, module.auth-service/src/main/java/ru/botanica/entities/Role.java, module.auth-service/src/main/java/ru/botanica/entities/User.java, module.auth-service/src/main/java/ru/botanica/exceptions/AppError.java, module.auth-service/src/main/java/ru/botanica/exceptions/ResourceNotFoundException.java, module.auth-service/src/main/java/ru/botanica/repositories/RoleRepository.java, module.auth-service/src/main/java/ru/botanica/repositories/UserRepository.java, module.auth-service/src/main/java/ru/botanica/services/RoleService.java, module.auth-service/src/main/java/ru/botanica/services/UserService.java, module.auth-service/src/main/java/ru/botanica/utils/JwtTokenUtil.java, module.auth-service/src/main/resources/application.properties, module.auth-service/src/main/resources/application.yaml, module.auth-service/src/main/resources/db/migration/V1__init_auth.sql, settings.gradle
Только авторизация для тестирования на фронте
=> Alexsenkin sprint2 add auth service

module.user-service/build.gradle, module.user-service/src/main/java/ru/botanica/UserServiceApplication.java, module.user-service/src/main/java/ru/botanica/controllers/UserController.java, module.user-service/src/main/java/ru/botanica/entities/users/User.java, module.user-service/src/main/java/ru/botanica/entities/users/UserDto.java, module.user-service/src/main/java/ru/botanica/entities/users/UserDtoMapper.java, module.user-service/src/main/java/ru/botanica/entities/users/UserRepository.java, module.user-service/src/main/java/ru/botanica/services/UserService.java, module.user-service/src/main/resources/application.yaml, module.user-service/src/test/java/ru/botanica/services/UserServiceTests.java
Настроил User-service.
Добавил сущность, ДТО, маппер для пользователя.
Добавил метод получения пользователя по идентификатору.
Покрыл тестами.
=> Sprint3 muzafarov

module.auth-service/src/main/java/ru/botanica/controllers/AuthController.java, module.auth-service/src/main/java/ru/botanica/dto/AppStatus.java, module.auth-service/src/main/java/ru/botanica/dto/UserDto.java, module.auth-service/src/main/java/ru/botanica/entities/Role.java, module.auth-service/src/main/java/ru/botanica/entities/User.java, module.auth-service/src/main/java/ru/botanica/services/UserService.java
Добавлена регистрация, бан, временное и постоянное удаление
=> Alexsenkin-sprint3-add auth-reg

module.plant-service/src/main/java/ru/botanica/services/PlantService.java
Немного напутали с кодом для заливки в develop, исправлено
=> Изменение конкретных растений 11.04.23

module.frontend-service/src/main/resources/static/PlantCard/PlantCard.html, module.frontend-service/src/main/resources/static/PlantCard/PlantCard.js, module.frontend-service/src/main/resources/static/Plants/Plants.js, module.frontend-service/src/main/resources/static/index.js, module.plant-service/src/main/java/ru/botanica/builders/PlantBuilder.java, module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantPhotoRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantRepository.java, module.plant-service/src/main/java/ru/botanica/services/PlantPhotoService.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java, module.plant-service/src/test/java/ru/botanica/services/PlantControllerTests.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java
Изменила PlantService в части добавления и изменения растения, чтобы не возникало ошибки при добавлении нового растения,
Добавила PlantPhotoService, потому что каждый сервис должен работать только со своим репозиторием
Добавила минимальный пока PlantBuilder , это просто потому что мне так удобнее
=> Исправление ошибки при добавлении нового растения с пустым id

module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/entities/plants/PlantDtoList.java, module.plant-service/src/main/java/ru/botanica/entities/plants/PlantDtoMapper.java, module.plant-service/src/main/java/ru/botanica/entities/plants/PlantDtoShort.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantRepository.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java
Исправления в коде: переписан метод обновления по аналогии с методом добавления, метод добавления разделен на несколько(билдер с инициализацией и методы добавления\обновления), создан PlantDtoList, чтобы не посылать огромное количество null-значений на фронт. Добавлены комментарии, добавлена недостающая зависимость на тест. Удален ненужный метод из PlantRepository
=> Исправления кода 12.04.23

module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/entities/responses/AppResponse.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantRepository.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java
Нагло сворован класс AppStatus из сервиса авторизации, потому что он был более чем исчерпывающим.
PlantController теперь передает обратно responseEntity. Добавлены два метода на проверку существования по имени и по id
=> Изменения в передаваемых файлах 12.04.23

module.frontend-service/src/main/resources/static/PlantCard/PlantCard.html, module.frontend-service/src/main/resources/static/PlantCard/PlantCard.js, module.frontend-service/src/main/resources/static/Plants/Plants.html, module.frontend-service/src/main/resources/static/Plants/Plants.js, module.frontend-service/src/main/resources/static/index.js
исправила некоторые ошибки связанные с пустым фото растения,
вынесла работу с растеием в отдельную фабрику
=> правки в работу с растением 

module.plant-service/src/main/java/ru/botanica/services/PlantService.java
Обновление передает теперь полное описание в поле для полного описания вместо короткого
=> Изменения в коде plant сервиса 13.04.23

module.user-service/src/main/java/ru/botanica/controllers/UserController.java, module.user-service/src/main/java/ru/botanica/entities/users/User.java, module.user-service/src/main/java/ru/botanica/entities/users/UserDto.java, module.user-service/src/main/java/ru/botanica/entities/users/UserRepository.java, module.user-service/src/main/java/ru/botanica/services/UserService.java, module.user-service/src/test/java/ru/botanica/services/UserServiceTests.java
Добавил методы по возврату идентификатора пользователя по его имени.
Тип user_id поменял с Integer на Long.
=> Добавлен возврат ИД пользователя по username

module.frontend-service/src/main/resources/static/PlantCard/PlantCard.html, module.frontend-service/src/main/resources/static/PlantCard/PlantCard.js, module.frontend-service/src/main/resources/static/Plants/Plants.js, module.frontend-service/src/main/resources/static/index.js
=> Sprint4 kuzmina 11.04

module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/entities/care/Care.java, module.plant-service/src/main/java/ru/botanica/entities/care/CareDto.java, module.plant-service/src/main/java/ru/botanica/entities/care/CareDtoMapper.java, module.plant-service/src/main/java/ru/botanica/entities/plantCares/PlantCare.java, module.plant-service/src/main/java/ru/botanica/entities/plantCares/PlantCareDto.java, module.plant-service/src/main/java/ru/botanica/entities/plantCares/PlantCareDtoMapper.java, module.plant-service/src/main/java/ru/botanica/entities/plants/Plant.java, module.plant-service/src/main/java/ru/botanica/entities/plants/PlantDto.java, module.plant-service/src/main/java/ru/botanica/entities/plants/PlantDtoMapper.java, module.plant-service/src/main/java/ru/botanica/repositories/CareRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantCareRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantPhotoRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantRepository.java, module.plant-service/src/main/java/ru/botanica/services/CareService.java, module.plant-service/src/main/java/ru/botanica/services/PlantPhotoService.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java
Сделаны сущности для таблиц care и plant_care. Для второй сущность создана, т.к. в таблице присутствуют дополнительные поля, которых нет в plants и care. Созданы Dto для этих объектов. Полностью написан mapper для Care класса, но в mapper'е для PlantCare точно верный метод написан только на создание Dto. mapToEntity лучше глянуть. Прям настоятельно рекомендую, вдруг у кого есть идеи получше. Из альтернатив сам увидел только query, что уже не хорошо, если мы работаем через объекты в остальном проекте. Модифицирована сущность Plant, в связи с этим доработан mapper. Созданы репозитории под новые сущности, CareService для обоих созданных репозиториев. Подправлены тесты, чтобы не вылезало ошибок. Готов метод на отправку фронту данных с учетом проводимых процедур
=> Список ухода для растений 14.04.23

module.plant-service/src/main/java/ru/botanica/builders/PlantBuilder.java, module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/dtos/CareDto.java, module.plant-service/src/main/java/ru/botanica/dtos/PlantCareDto.java, module.plant-service/src/main/java/ru/botanica/dtos/PlantDto.java, module.plant-service/src/main/java/ru/botanica/dtos/PlantDtoShort.java, module.plant-service/src/main/java/ru/botanica/dtos/PlantPhotoDto.java, module.plant-service/src/main/java/ru/botanica/dtos/maps/PlantDtoMap.java, module.plant-service/src/main/java/ru/botanica/entities/Care.java, module.plant-service/src/main/java/ru/botanica/entities/Plant.java, module.plant-service/src/main/java/ru/botanica/entities/PlantCare.java, module.plant-service/src/main/java/ru/botanica/entities/PlantPhoto.java, module.plant-service/src/main/java/ru/botanica/entities/PlantSpecifications.java, module.plant-service/src/main/java/ru/botanica/mappers/CareDtoMapper.java, module.plant-service/src/main/java/ru/botanica/mappers/PlantCareDtoMapper.java, module.plant-service/src/main/java/ru/botanica/mappers/PlantDtoMapper.java, module.plant-service/src/main/java/ru/botanica/mappers/PlantPhotoDtoMapper.java, module.plant-service/src/main/java/ru/botanica/repositories/CareRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantCareRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantPhotoRepository.java, module.plant-service/src/main/java/ru/botanica/repositories/PlantRepository.java, module.plant-service/src/main/java/ru/botanica/responses/AppResponse.java, module.plant-service/src/main/java/ru/botanica/services/CareService.java, module.plant-service/src/main/java/ru/botanica/services/PlantPhotoService.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java, module.plant-service/src/test/java/ru/botanica/services/PlantControllerTests.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java
Попробовал оживить тест, после того, как он не возвращал ожидаемые id и filePath в Dto, но не смог. Закомментировал проверку этих строчек, сделал так, что filePath прописывается за тест только один раз(при инициализации фото), дописал ожидаемый итог на используемый в addNewPlant метод из PlantPhotoService
=> Правки кода 17.04.23

module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/dtos/CareDtoShort.java, module.plant-service/src/main/java/ru/botanica/entities/CareSpecifications.java, module.plant-service/src/main/java/ru/botanica/mappers/CareDtoMapper.java, module.plant-service/src/main/java/ru/botanica/services/CareService.java, module.plant-service/src/test/java/ru/botanica/services/PlantControllerTests.java, module.user-service/src/test/java/ru/botanica/services/UserServiceTests.java
Создана спецификация для Care, создан метод возвращающий список CareDtoShort(id, name), если Care.isActive=true. Добавлена зависимость от CareService в контроллер, соответствующая зависимость добавлена в PlantControllerTests UserServiceTests лежал с ошибкой: должны быть boolean вместо int, так что 0 изменено на false, а 1 - на true. Теперь компилирует нормально
=> Добавление эндпоинта "/care_types" 18.04.23

module.plant-service/build.gradle, module.plant-service/src/main/java/ru/botanica/dtos/CareDto.java, module.plant-service/src/main/java/ru/botanica/dtos/PlantCareDto.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java, module.user-service/build.gradle, module.user-service/src/test/java/ru/botanica/services/UserServiceTests.java
=> Sprint5 muzafarov

module.auth-service/src/main/java/ru/botanica/services/UserService.java, module.user-service/src/main/java/ru/botanica/controllers/UserPlantsController.java, module.user-service/src/main/java/ru/botanica/dto/UserPlantsShortDto.java, module.user-service/src/main/java/ru/botanica/dto/UserPlantsShortDtoMapper.java, module.user-service/src/main/java/ru/botanica/repositories/PlantRepository.java, module.user-service/src/main/java/ru/botanica/repositories/UserPlantsRepository.java, module.user-service/src/main/java/ru/botanica/services/UserPlantsService.java
Доработка user-service: добавление растения пользователя, изменение isActive и isBanned для растения пользователя
=> Alexsenkin sprint 5 modify user service

module.user-service/src/main/java/ru/botanica/controllers/UserController.java, module.user-service/src/main/java/ru/botanica/services/UserService.java
Добавлены методы получения списка пользователей
=> Добавил получение всех пользователей

module.plant-service/src/main/java/ru/botanica/controllers/PlantController.java, module.plant-service/src/main/java/ru/botanica/services/CareService.java, module.plant-service/src/main/java/ru/botanica/services/PlantPhotoService.java, module.plant-service/src/main/java/ru/botanica/services/PlantService.java, module.plant-service/src/test/java/ru/botanica/services/PlantServiceTests.java
Сохранение растения собрано в один метод из трех разных(растение, фото, список ухода), контроллер и соответствующий тест обновлены в соответствии с данными изменениями
=> Правки plant-service 25.04.23

module.user-service/src/main/java/ru/botanica/controllers/UserPlantsController.java, module.user-service/src/main/java/ru/botanica/services/UserPlantsService.java
Доработка user-service добавлен енд-поинт добавления в журнал ухода
=> Доработка user-service добавлен енд-поинт добавления в журнал ухода

module.frontend-service/src/main/resources/static/PlantCard/PlantCard.html, module.frontend-service/src/main/resources/static/PlantCard/PlantCard.js, module.frontend-service/src/main/resources/static/Plants/Plants.html, module.frontend-service/src/main/resources/static/Plants/Plants.js, module.frontend-service/src/main/resources/static/User/UserProfile.html, module.frontend-service/src/main/resources/static/index.js
=> исправление багов

module.user-service/src/main/java/ru/botanica/controllers/GlobalExceptionHandler.java, module.user-service/src/main/java/ru/botanica/controllers/UserController.java, module.user-service/src/main/java/ru/botanica/controllers/UserPlantsController.java, module.user-service/src/main/java/ru/botanica/exceptions/ServerHandleException.java, module.user-service/src/main/java/ru/botanica/services/UserPlantsService.java, module.user-service/src/main/java/ru/botanica/services/UserService.java, module.user-service/src/test/java/ru/botanica/services/UserServiceTests.java
Доработка user-service: добавлены логи и обработка исключений
Спасибо Vito за GlobalExceptionHandler)
=> Доработка user-service: добавлены логи и обработка исключений

module.frontend-service/src/main/resources/static/PlantCard/PlantCard.html, module.frontend-service/src/main/resources/static/Plants/Plants.html, module.frontend-service/src/main/resources/static/Plants/Plants.js
=> исправлен баг с поиском
